
project_id = "jawtwwwelxaaprzsqfyp"

[api]
enabled = true

[db]
version = 0

[realtime]
enabled = true

[storage]
enabled = false

[auth]
enabled = true

[functions.verify-token]
verify_jwt = false

[functions.auto-delete-entries]
verify_jwt = false

