
project_id = "jawtwwwelxaaprzsqfyp"

[api]
enabled = true

[db]
version = 0

[realtime]
enabled = true
# Enable specific changers for the anamnes_entries table
[realtime.postgres_changes]
schemas = ["public"]
tables = ["anamnes_entries", "users"]

[storage]
enabled = false

[auth]
enabled = true

[functions.verify-token]
verify_jwt = false

[functions.auto-delete-entries]
verify_jwt = false

[functions.issue-form-token]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.save-draft]
verify_jwt = false

[functions.clerk-auth-webhook]
verify_jwt = false

[functions.notify-optician-driving-license]
verify_jwt = false

[functions.cleanup-access-logs]
verify_jwt = false

[functions.repair-missing-summaries]
verify_jwt = false

[functions.get-store-forms]
verify_jwt = false

[functions.verify-system-admin]
verify_jwt = false
